# Site
name: "The Art of Marketing Science"
title: "The Art of Marketing Science"
description: "Data science in marketing with practical examples"
meta_description: "Data science in marketing with practical examples"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-112419219-1'
disqus: 'https-fongmanfong-github-io'
mailchimp-list: 'https://github.us20.list-manage.com/subscribe/post?u=7e19d52d70f2181f9f5f666db&amp;id=2158c5e28a'

include: ["_pages"]
permalink: /:title/

# Authors
authors:
  art_of_marketing_science:
    name: "Art of Marketing Science"
    display_name: "Art of Marketing Science"
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    avatar: /assets/images/avatar/purple.png
    email: fongjason23@gmail.com
    web: https://fongmanfong.github.io
    twitter: https://twitter.com/fongmanfong
    description: "Using data science & engineering to understand and solve marketing problems"
  data_sandbox:
    name: "Data Sandbox"
    display_name: "Data Sandbox"
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    avatar: /assets/images/avatar/green.png
    email: fongjason23@gmail.com
    web: https://fongmanfong.github.io
    twitter: https://twitter.com/fongmanfong
    description: "Playing is the most natural way to learn. These are the artifacts in my sandbox playground."
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge