# Site
name: "The Art of Marketing Science"
title: "The Art of Marketing Science"
description: "A blog about data stuff"
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /fongmanfong
google_analytics: 'UA-112419219-1'
disqus: 'https-fongmanfong-github-io'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Jason Fong
    display_name: fongmanfong
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: fongjason23@gmail.com
    web: https://fongmanfong.github.io
    twitter: https://twitter.com/fongmanfong
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  # john:
  #   name: John
  #   display_name: John
  #   gravatar: b1cc14991db7a456fcd761680bbc8f81
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge